name: Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        
    - name: Install Dependencies
      run: |
        npm install -g npm@latest  # Ensure latest npm version
        make install-dev
        
    - name: Run Linting
      run: make lint
